Ponder.registry((event) => {
	let mechanismTypes = [
		"nature",
		"wooden",
		"stone",
		"iron",
		"copper",
		"andesite",
		"photosensitive",
		"gold",
		"cobalt",
		"nether",
		"thermal",
		"reinforced",
		"resonant",
		"railway",
		"ender",
		"light_engineering",
		"heavy_engineering",
		"enchanted",
		"smart",
		"computing",
		"tier_1_aviation",
		"tier_2_aviation",
		"tier_3_aviation",
		"tier_4_aviation",
		"basic_mekanism",
		"advanced_mekanism",
		"elite_mekanism",
		"ultimate_mekanism",
		"air_tight",
		"nuclear",
		"antimatter",
		"coil",
		"sculk",
		"colorful",
		"creative",
		"potion",
		"precision",
		"redstone",
		"bronze",
		"pig_iron"
	]
	mechanismTypes.forEach((type)=>{
	event.create(`cmi:${type}_machine`)
		.scene("1", "Hey,my friend,this is for test!", `cmi:dev_ftb/ftb_${type}`, (scene) => {
			scene.showStructure()
			// 参数临时直接改
			scene.scaleSceneView(0.2)
		})
	})
})