ServerEvents.recipes((event) => {
	let { mekanism } = event.getRecipes()

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:brine", 200))
		.fluidOutput(Fluid.tag("tag", "forge:brine", 200))
		.gasInput(MekanismType.Gas.of("mekanism:brine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:brine", 200))
		.id("mekanism:rotary/brine")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:chlorine", 200))
		.fluidOutput(Fluid.tag("tag", "forge:chlorine", 200))
		.gasInput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.id("mekanism:rotary/chlorine")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:ethene", 200))
		.fluidOutput(Fluid.tag("tag", "forge:ethene", 200))
		.gasInput(MekanismType.Gas.of("mekanism:ethene", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:ethene", 200))
		.id("mekanism:rotary/ethene")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:hydrofluoric_acid", 200))
		.fluidOutput(Fluid.tag("tag", "forge:hydrofluoric_acid", 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.id("mekanism:rotary/hydrofluoric_acid")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:hydrogen_chloride", 200))
		.fluidOutput(Fluid.tag("tag", "forge:hydrogen_chloride", 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.id("mekanism:rotary/hydrogen_chloride")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:hydrogen", 200))
		.fluidOutput(Fluid.tag("tag", "forge:hydrogen", 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.id("mekanism:rotary/hydrogen")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:lithium", 200))
		.fluidOutput(Fluid.tag("tag", "forge:lithium", 200))
		.gasInput(MekanismType.Gas.of("mekanism:lithium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:lithium", 200))
		.id("mekanism:rotary/lithium")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:oxygen", 200))
		.fluidOutput(Fluid.tag("tag", "forge:oxygen", 200))
		.gasInput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.id("mekanism:rotary/oxygen")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:sodium", 200))
		.fluidOutput(Fluid.tag("tag", "forge:sodium", 200))
		.gasInput(MekanismType.Gas.of("mekanism:sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sodium", 200))
		.id("mekanism:rotary/sodium")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:steam", 200))
		.fluidOutput(Fluid.tag("tag", "forge:steam", 200))
		.gasInput(MekanismType.Gas.of("mekanism:steam", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:steam", 200))
		.id("mekanism:rotary/steam")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:sulfur_dioxide", 200))
		.fluidOutput(Fluid.tag("tag", "forge:sulfur_dioxide", 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.id("mekanism:rotary/sulfur_dioxide")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:sulfur_trioxide", 200))
		.fluidOutput(Fluid.tag("tag", "forge:sulfur_trioxide", 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.id("mekanism:rotary/sulfur_trioxide")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:sulfuric_acid", 200))
		.fluidOutput(Fluid.tag("tag", "forge:sulfuric_acid", 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.id("mekanism:rotary/sulfuric_acid")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:superheated_sodium", 200))
		.fluidOutput(Fluid.tag("tag", "forge:superheated_sodium", 200))
		.gasInput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.id("mekanism:rotary/superheated_sodium")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:uranium_hexafluoride", 200))
		.fluidOutput(Fluid.tag("tag", "forge:uranium_hexafluoride", 200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.id("mekanism:rotary/uranium_hexafluoride")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:uranium_oxide", 200))
		.fluidOutput(Fluid.tag("tag", "forge:uranium_oxide", 200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.id("mekanism:rotary/uranium_oxide")

	mekanism.rotary()
		.fluidInput(Fluid.tag("tag", "forge:water", 200))
		.fluidOutput(Fluid.tag("tag", "forge:water", 200))
		.gasInput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.id("mekanism:rotary/water")
})